- name: update all systems
  #hosts: "*"
  become: yes
  tasks:
    - ping:
      register: ping_result
      ignore_unreachable: true
    - fail:
        msg: "Controlla i server che non rispondono"
      when: ping_result.unreachable is defined
      any_errors_fatal: true
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        upgrade: 'yes'
