- name: Install htop
  hosts: "*"
  become: yes
  tasks:
    - ping:
      register: ping_result
      ignore_unreachable: true
    - name: Install htop
      apt:
        update_cache: yes
        name: htop
        state: present
